=== DevRel-Foundation/persona-library/src/schemas/persona.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "persona.schema.json",
    "$id": "https://github.com/DevRel-Foundation/persona-library/blob/main/src/schema/persona.json",
    "title": "Personas",
    "description": "Developer Relations Foundation Persona Library.",
    "version": "1.0",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "The schema that can be used for validation. Can be relative file path or URL.",
            "type": "string"
        },
        "id": {
            "description": "A unique id to help identify this persona",
            "type": "string"
        },
        "parent": {
            "type": "array",
            "description": "Definition of a persona that this one extends with additional specific attributes",
            "items": {
                "type": "string"
            }
        },
        "label": {
            "description": "A unique label to help identify this persona",
            "type": "string"
        },
        "narrative": {
            "description": "A free-form description that can be used to tell the story of the persona.",
            "type": "string"
        },
        "segment": {
            "description": "The vertical or industry segment as a modifier on the behaviors of a persona.",
            "type": "string"
        },
        "organization": {
            "description": "See traits/organization.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "maturity": {
                    "type": "string",
                    "description": "The maturity of the organization as a modifier on the persona behaviors.",
                    "enum": ["startup", "legacy", "*"]
                },
                "gtm": {
                    "type": "string",
                    "description": "The go to market strategy of the organization as a modifier on the persona.",
                    "enum": ["b2b", "b2c", "b2d", "*"]
                }
            },
            "required": [],
            "additionalProperties": false
        },
        "awareness": {
            "description": "See traits/learning.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "description": "The business relationship between the persona's organization and yours.",
                    "enum": ["pro", "user", "partner", "lead", "unaware", "ex", "*"]
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "format": {
                                "type": "string",
                                "enum": ["blog", "newsletter", "video", "product", "docs", "social", "web"]
                            },
                            "url": {
                                "type": "string"
                            },
                            "level": {
                                "type": "string",
                                "enum": ["100", "200", "300", "*"]
                            }
                        }
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "additionalProperties": false
        },
        "adoption": {
            "description": "Adoption traits",
            "type": "object",
            "properties": {
                "curve": {
                    "type": "string",
                    "enum": ["innovator", "early", "majority", "late", "laggard", "*"]
                },
                "modality": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["problem", "learn", "understand", "info", "guide", "*"]
                    }
                }
            }
        },
        "role": {
            "description": "See traits/role.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "function": {
                    "type": "string",
                    "enum": ["dev", "art", "biz", "mix", "*"]
                },
                "experience": {
                    "description": "The stage of career is an indicator for how familiar a person may be with the skills and expectations of their role. \nThis attribute is about the progression for a specific role, not a person. Somebody may have extensive professional experience, but if they've taken on a new role in a new industry for the purposes of defining the persona it has reset the clock.",
                    "type": "string",
                    "enum": ["early", "mid", "pro", "*"]
                },
                "level": {
                    "type": "string",
                    "description": "The placement and influence this person has on the organization.",
                    "enum": ["ic", "lead", "exec", "infl", "*"]
                },
                "responsibilities": {
                    "type": "array",
                    "description": "The broad job tasks this persona must execute on as part of the duties of their role.",
                    "items": {
                        "type": "string",
                        "enum": ["coding", "reviewing", "planning", "reporting", "marketing", "financials", "strategy", "design", "writing", "*"]
                    }
                },
                "titles": {
                    "type": "array",
                    "description": "A list of typical job titles this persona may hold.",
                    "items": {
                        "type": "string"
                    }
                },
                "x-titles": {
                    "type": "array",
                    "description": "Extended set of titles for this persona. Merges instead of replaces.",
                    "items": {
                        "type": "string"
                    }
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-creative", "drf-test", "drf-build", "drf-cmm", "drf-email", "drf-cms", "drf-db"]
                    }
                },
                "x-tools": {
                    "type": "array",
                    "description": "Extended set of tools for this persona. Merges instead of replaces.",
                    "items": {
                        "type": "string",
                        "enum": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-creative", "drf-test", "drf-build", "drf-cmm", "drf-email", "drf-cms", "drf-db"]
                    }
                },
                "technologies": {
                    "type": "object",
                    "properties": {
                        "languages": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "environments": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "education": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "skills": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "required": ["responsibilities", "level"],
            "additionalProperties": false
        },
        "motivations": {
            "type": "object",
            "properties": {
                "likes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dislikes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "x-likes": {
                    "type": "array",
                    "description": "Additional extended likes that do not replace inherited definitions.",
                    "items": {
                        "type": "string"
                    }
                },
                "x-dislikes": {
                    "type": "array",
                    "description": "Additional extended dislikes that do not replace inherited definitions.",
                    "items": {
                        "type": "string"
                    }
                }

            },
            "additionalProperties": false
        },
        "strategies": {
            "type": "object",
            "properties": {
                "marketing": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sales": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "finance": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "design": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "devex": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "education": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "required": ["id", "label"],
    "additionalProperties": false
}

=== DevRel-Foundation/persona-library/data/personas/mix-early-infl.json
{
    "id": "mix-early-infl",
    "label": "Andy Advocate",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "mix",
        "level": "infl",
        "experience": "*",
        "responsibilities": ["coding", "reviewing"],
        "titles": [
            "Developer Advocate",
            "Developer Evangelist",
            "Head of Developer Relations"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"]
    },
    "adoption": {
        "curve": "early"
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://slashdot.org"}
        ],
        "events": ["drf-devrelcon.dev"]
    }
}

=== DevRel-Foundation/persona-library/data/personas/art.json
{
    "id": "art",
    "label": "UX Designer",
    "narrative": "Somebody who leans more on creativity than technical skill has a strong sense for aesthetics and user experience. They often will work paired up with development oriented teams to execute on a vision, with the ability to express the desired end state to reach a creative design vision.",
    "organization": {
        "gtm": "*",
        "maturity": "*"
    },
    "role": {
        "function": "art",
        "level": "*",
        "experience": "*",
        "responsibilities": ["design", "writing"],
        "titles": [
            "UX Engineer",
            "Creative Technologist",
            "UI Developer",
            "Front-end Developer",
            "Interaction Designer"
        ],
        "tools": ["drf-creative", "drf-cms", "drf-ticketing", "drf-comms"]
    },
    "awareness": {
        "channels": [
                {"format": "blog", "url": "https://css-tricks.com"},
                {"format": "social", "url": "https://reddit.com/r/UXDesign"}
        ],
        "events": ["drf-config.figma.com", "drf-sigchi.org"]
    },
    "motivations": {
        "likes": [
            "Wants to see visualizations, mockups, and designs to better understand concepts rather than text.",
            "Iterative processes and gradual improvement.",
            "Wants a better understanding of user goals",
            "Will pick up on and appreciate moments of delight you add to your user interfaces."
        ],
        "dislikes": [
            "Despises working within design constraints and brand guidelines that limit creative influence.",
            "Bad design execution, expects form prioritized over function.",
            "Wants to achieve a balance creative objectives with technical constraints even when mutually exclusive.",
            "Products that have not taken accessibility into consideration"
        ]
    },
    "strategies": {
        "design": [
            "Design products or services that are more free-form and flexible.",
            "Provide open access to brand guidelines and design systems."
        ],
        "product": [
            "Play close attention to precision in fonts, colors, and other design elements."
        ],
        "education": [
            "Provide open-ended inspirational examples in tutorials or creative experiential learning.",
            "Include graphics and pictures of user interfaces that complement source code or textual descriptions."
        ],
        "communications": [
            "Use visual communicaton such as infographics and guides."
        ],
        "sales": [
            "Reference customers and examples that show how well designed solutions look when complete."
        ],
        "marketing": [
            "Provide gallery of inspiration from finished products."
        ]
    }
}

=== DevRel-Foundation/persona-library/data/personas/dev.json
{
    "id": "dev",
    "label": "Software Developer",
    "role": {
        "function": "dev",
        "responsibilities": ["coding", "reviewing"],
        "level": "ic",
        "titles": [
            "Software Engineer",
            "Software Developer",
            "Full-Stack Developer",
            "Sr. Software Engineer",
            "Staff Software Engineer",
            "Principal Software Engineer",
            "Tech Lead"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"]
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://slashdot.org"}
        ],
        "events": [ ]
    }
}

=== DevRel-Foundation/persona-library/data/sets/openssf.org/ssf-biz-exec.json
{
    "id": "ssf-biz-exec",
    "label": "Charli CEO",
    "narrative": "Leadership role for an enterprise or organization.",
    "organization": {
        "gtm": "*",
        "maturity": "*"
    },
    "role": {
        "function": "biz",
        "level": "exec",
        "experience": "*",
        "responsibilities": [],
        "titles": [
            "CISO",
            "CTO",
            "CEO"
        ],
        "tools": [ ]
    },
    "awareness": {
        "channels": [ ],
        "events": [ ]
    },
    "motivations": {
        "likes": [
            "Networking, business development, and collaborating on enterprise engagement."
        ],
        "dislikes": [
        ]
    },
    "strategies": {
        "design": [
        ],
        "product": [
        ],
        "education": [
            "Policy summits and case studies are valuable."
        ],
        "communications": [
            "Integration with other Linux Foundation projects the organization also relies upon.",
            "Cross-project engagement and enterprise adoption messaging."
        ],
        "sales": [
        ],
        "marketing": [
        ]
    }
}

=== DevRel-Foundation/persona-library/data/sets/dev-rel.org/biz-mktg.json
{
    "label": "Markety Mark",
    "id": "biz-mktg",
    "narrative": "This persona joined the DevRel Foundation because the developer segment is important for their role. They have a marketing background and contribute to marketing campaigns that are aimed at developers.",
    "organization": {
        "gtm": "*",
        "maturity": "*"
    },
    "role": {
        "function": "biz",
        "level": "*",
        "experience": "*",
        "responsibilities": ["marketing", "design", "writing", "planning", "strategy"],
        "titles": [
            "Product Marketing Manager",
            "Developer Marketing Manager",
            "Field Marketing Manager",
            "Events Manager",
            "Content Marketing Manager",
            "Social Media Manager",
            "Marketing Operations Manager",
            "Growth Marketing Manager",
            "General Manager",
            "Developer Ecosystem Strategy",
            "Digital Marketing",
            "Account Director",
            "VP, Sales",
            "VP, Marketing"
        ],
        "tools": []
    },
    "awareness": {
        "channels": [
                {"format": "web", "url": "https://evansdata.com"},
                {"format": "web", "url": "https://developermarketing.io"},
                {"format": "social", "url": "https://linkedin.com"}
        ],
        "events": [
            "drf-devrelcon.com", 
            "drf-developerweek.com", 
            "drf-events.productmarketingalliance.com"
        ]
    },
    "motivations": {
        "likes": [
            "Doing a good job in their role and want to find new skills and techniques to deliver their messages to market."
        ],
        "dislikes": [
            "Using tools like GitHub or Discord that feel like they are made for a more technical audience."
        ]
    },
    "strategies": {
        "design": [
        ],
        "product": [
        ],
        "education": [
            "Show case studies and examples of how to successfully target developer campaigns effectively."
        ],
        "communications": [
            "Want to promote a campaign they are working on to this community, so give them a space to share where it would be welcome."
        ],
        "sales": [
        ],
        "marketing": [
            "Reach out to marketers specifically who target developers to let them know they are invited to participate and join."
        ]
    }
}

=== DevRel-Foundation/persona-library/data/sets/dev-rel.org/all-early.json
{
    "id": "all-early",
    "parent": ["mix-infl", "dev-infl"],
    "label": "Wally Wants-to-Advocate",
    "narrative": "Early to a developer relations role and wants to learn from more experienced.",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "mix",
        "level": "infl",
        "experience": "*",
        "responsibilities": ["coding", "reviewing"],
        "titles": [
            "Developer Evangelist",
            "Community Manager",
            "Head of Developer Relations"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"]
    },
    "adoption": {
        "curve": "early"
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://slashdot.org"}
        ],
        "events": ["drf-devrelcon.dev"]
    },
    "motivations": {
        "x-likes": [
            "Sharing knowledge to build their personal reputation and brand in technical communities"
        ],
        "x-dislikes": [
            "Often overwhelmed with cross-functional asks from a community with more members than hours in the day."
        ]
    }
}

=== DevRel-Foundation/persona-library/data/personas/devops-dev.json
{
    "id": "devops-dev",
    "parent": ["dev"],
    "label": "DevOps Dot",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "dev",
        "level": "*",
        "responsibilities": ["coding", "reviewing"],
        "titles": [
            "DevOps Engineer"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"],
        "technologies": {
            "languages": [ ],
            "environments": [ ],
            "skills": [ ]
        }
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://stackoverflow.com"}
        ],
        "events": [ ]
    },
    "adoption": {
        "curve": "*",
        "modality": []
    },
    "motivations": {
        "x-likes": [],
        "x-dislikes": [
        ]
    },
    "strategies": {
        "design": [],
        "product": [],
        "education": [],
        "communications": [],
        "sales": [],
        "marketing": []
    }
}

=== DevRel-Foundation/persona-library/data/sets/dev-rel.org/mix-lead.json
{
    "id": "mix-lead",
    "parent": ["dev", "biz"],
    "label": "Henry Head",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "mix",
        "level": "infl",
        "experience": "*",
        "responsibilities": ["coding", "reviewing"],
        "titles": [
            "Head of Developer Relations"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"]
    },
    "adoption": {
        "curve": "early"
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://slashdot.org"}
        ],
        "events": ["drf-devrelcon.dev"]
    },
    "motivations": {
        "x-likes": [
        ],
        "x-dislikes": [
        ]
    }
}
