=== DevRel-Foundation/persona-library/src/schemas/persona.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "persona.schema.json",
    "$id": "https://github.com/DevRel-Foundation/persona-library/blob/main/src/schema/persona.json",
    "title": "Personas",
    "description": "Developer Relations Foundation Persona Library.",
    "version": "1.0",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "The schema that can be used for validation. Can be relative file path or URL.",
            "type": "string"
        },
        "id": {
            "description": "A unique id to help identify this persona",
            "type": "string"
        },
        "parent": {
            "type": "array",
            "description": "Definition of a persona that this one extends with additional specific attributes",
            "items": {
                "type": "string"
            }
        },
        "label": {
            "description": "A unique label to help identify this persona",
            "type": "string"
        },
        "narrative": {
            "description": "A free-form description that can be used to tell the story of the persona.",
            "type": "string"
        },
        "segment": {
            "description": "The vertical or industry segment as a modifier on the behaviors of a persona.",
            "type": "string"
        },
        "organization": {
            "description": "See traits/organization.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "maturity": {
                    "type": "string",
                    "description": "The maturity of the organization as a modifier on the persona behaviors.",
                    "enum": ["startup", "legacy", "*"]
                },
                "gtm": {
                    "type": "string",
                    "description": "The go to market strategy of the organization as a modifier on the persona.",
                    "enum": ["b2b", "b2c", "b2d", "*"]
                }
            },
            "required": [],
            "additionalProperties": false
        },
        "awareness": {
            "description": "See traits/learning.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "description": "The business relationship between the persona's organization and yours.",
                    "enum": ["pro", "user", "partner", "lead", "unaware", "ex", "*"]
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "format": {
                                "type": "string",
                                "enum": ["blog", "newsletter", "video", "product", "docs", "social", "web"]
                            },
                            "url": {
                                "type": "string"
                            },
                            "level": {
                                "type": "string",
                                "enum": ["100", "200", "300", "*"]
                            }
                        }
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "additionalProperties": false
        },
        "adoption": {
            "description": "Adoption traits",
            "type": "object",
            "properties": {
                "curve": {
                    "type": "string",
                    "enum": ["innovator", "early", "majority", "late", "laggard", "*"]
                },
                "modality": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["problem", "learn", "understand", "info", "guide", "*"]
                    }
                }
            }
        },
        "role": {
            "description": "See traits/role.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "function": {
                    "type": "string",
                    "enum": ["dev", "art", "biz", "mix", "*"]
                },
                "experience": {
                    "description": "The stage of career is an indicator for how familiar a person may be with the skills and expectations of their role. \nThis attribute is about the progression for a specific role, not a person. Somebody may have extensive professional experience, but if they've taken on a new role in a new industry for the purposes of defining the persona it has reset the clock.",
                    "type": "string",
                    "enum": ["early", "mid", "pro", "*"]
                },
                "level": {
                    "type": "string",
                    "description": "The placement and influence this person has on the organization.",
                    "enum": ["ic", "lead", "exec", "infl", "*"]
                },
                "responsibilities": {
                    "type": "array",
                    "description": "The broad job tasks this persona must execute on as part of the duties of their role.",
                    "items": {
                        "type": "string",
                        "enum": ["coding", "reviewing", "planning", "reporting", "marketing", "financials", "strategy", "design", "writing", "*"]
                    }
                },
                "titles": {
                    "type": "array",
                    "description": "A list of typical job titles this persona may hold.",
                    "items": {
                        "type": "string"
                    }
                },
                "x-titles": {
                    "type": "array",
                    "description": "Extended set of titles for this persona. Merges instead of replaces.",
                    "items": {
                        "type": "string"
                    }
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-creative", "drf-test", "drf-build", "drf-cmm", "drf-email", "drf-cms", "drf-db"]
                    }
                },
                "x-tools": {
                    "type": "array",
                    "description": "Extended set of tools for this persona. Merges instead of replaces.",
                    "items": {
                        "type": "string",
                        "enum": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-creative", "drf-test", "drf-build", "drf-cmm", "drf-email", "drf-cms", "drf-db"]
                    }
                },
                "technologies": {
                    "type": "object",
                    "properties": {
                        "languages": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "environments": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "education": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "skills": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "required": ["responsibilities", "level"],
            "additionalProperties": false
        },
        "motivations": {
            "type": "object",
            "properties": {
                "likes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dislikes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "x-likes": {
                    "type": "array",
                    "description": "Additional extended likes that do not replace inherited definitions.",
                    "items": {
                        "type": "string"
                    }
                },
                "x-dislikes": {
                    "type": "array",
                    "description": "Additional extended dislikes that do not replace inherited definitions.",
                    "items": {
                        "type": "string"
                    }
                }

            },
            "additionalProperties": false
        },
        "strategies": {
            "type": "object",
            "properties": {
                "marketing": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sales": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "finance": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "design": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "devex": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "education": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "required": ["id", "label"],
    "additionalProperties": false
}

=== DevRel-Foundation/persona-library/data/personas/dev-lead.json
{
    "id": "dev-lead",
    "parent": ["dev"],
    "label": "Larry Lead",
    "segment": "*",
    "narrative": "Somebody who has transitioned into a leadership role with previous software engineering experience. They have not only strong foundations for software syntax and design patterns but have broadened their skillset to include people management, project management, and other business concerns.",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "dev",
        "level": "lead",
        "responsibilities": ["reviewing", "planning", "reporting"],
        "titles": [
            "Tech Lead",
            "Engineering Manager",
            "Director, Engineering",
            "Director, IT",
            "VP, Engineering",
            "Software Development Manager",
            "Head of Engineering"
        ],
        "tools": ["drf-ticketing", "drf-comms"],
        "technologies": {
            "languages": [ ],
            "environments": [ ],
            "skills": [ ]
        }
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://slashdot.org"}
        ],
        "events": ["drf-leaddev.com"]
    },
    "adoption": {
        "curve": "*",
        "modality": []
    },
    "motivations": {
        "x-likes": [
            "Lead Devs make technical decisions that can drive business impact through new revenue-generating products",
            "Lead Devs mentor and growing new engineers by sharing their experiences",
            "Lead Devs often think in terms of efficiency, not just speed, but a conservation of resources to achieve a goal.",
            "Lead Devs choose safe options that have available talent on the market to support, extend, and use.",
            "Lead Devs look for solutions that do not require their existing teams to ramp up on too many new technologies.",
            "Lead Devs view into implementation timelines and resource requirements on the team",
            "Lead Devs prefer an architectural view of who owns which services/components"
        ],
        "x-dislikes": [
            "Lead Devs have very low tolerance for fluff and sales approaches that over-promise or are factually incorrect.",
            "Lead Devs are wary of vendor lock-in that restricts solution choice later.",
            "Lead Devs are concerned about integration issues and long-term maintenance ramifications after a project completes. They can become burdened by ongoing technical debt."
        ]
    },
    "strategies": {
        "design": [
        ],
        "product": [
            "Will be interested in integrations with other systems in use.",
            "Will be interested in maintenance and operational concerns of running the solution.",
            "Will want to understand disaster recovery procedures and plans to insure reliability"
        ],
        "education": [
            "Will want to understand learning curve and ramp-up time for engineering teams.",
            "Content such as white papers, will be ok if content is gated.",
            "Panels or roundtable discussions sharing lessons learned."
        ],
        "communications": [
            "Provide both technical and business context to aid with decision-making",
            "Will want to understand the size of the community so may check forums such as StackOverflow, Quora, etc. for questions and responses."
        ],
        "sales": [
            "Insure operational concerns around reliability, uptime, and support are all addressed.",
            "Be prepared for security, privacy, data retention, and other compliance considerations.",
            "May often need to work through a provisioning team or other agents who negotiate on their behalf.",
            "Demonstrate an understanding of their complete technical environment and compatibility for how solution fits in."
        ],
        "marketing": [
            "Metrics and proof points that back up scalability and performance claims.",
            "ROI and pricing calculators to work out total cost of ownership",
            "Case studies of other respected organizations that have had successful adoption and usage"
        ]
    }
}

=== DevRel-Foundation/persona-library/data/personas/security-biz-early-exec.json
{
    "id": "security-biz-early-exec",
    "label": "Security Buyer",
    "segment": "security",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    }, 
    "role": {
        "function": "biz",
        "level": "exec",
        "experience": "*",
        "responsibilities": ["financials", "strategy"],
        "tools": [],
        "titles": [
            "Chief Information Security Officer",
            "CISO",
            "VP, Security",
            "Head of Security"
        ]
    },
    "adoption": {
        "curve": "early",
        "modality": ["understand", "info"]
    },
    "awareness": {
        "channels": [
                {"format": "blog", "url": "https://www.cio.com/", "level": "200"},
                {"format": "newsletter", "url": "https://tldrsec.com/", "level":"200"},
                {"format": "blog", "url": "https://krebsonsecurity.com/"},
                {"format": "newsletter", "url": "https://www.returnonsecurity.com/"}
        ],
        "events": [
            "drf-rsaconference.com"
        ]
    }
}
