=== DevRel-Foundation/persona-library/src/schemas/persona.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "persona.schema.json",
    "$id": "https://github.com/DevRel-Foundation/persona-library/blob/main/src/schema/persona.json",
    "title": "Personas",
    "description": "Developer Relations Foundation Persona Library.",
    "version": "1.0",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "The schema that can be used for validation. Can be relative file path or URL.",
            "type": "string"
        },
        "id": {
            "description": "A unique id to help identify this persona",
            "type": "string"
        },
        "parent": {
            "type": "array",
            "description": "Definition of a persona that this one extends with additional specific attributes",
            "items": {
                "type": "string"
            }
        },
        "label": {
            "description": "A unique label to help identify this persona",
            "type": "string"
        },
        "narrative": {
            "description": "A free-form description that can be used to tell the story of the persona.",
            "type": "string"
        },
        "segment": {
            "description": "The vertical or industry segment as a modifier on the behaviors of a persona.",
            "type": "string"
        },
        "organization": {
            "description": "See traits/organization.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "maturity": {
                    "type": "string",
                    "description": "The maturity of the organization as a modifier on the persona behaviors.",
                    "enum": ["startup", "legacy", "*"]
                },
                "gtm": {
                    "type": "string",
                    "description": "The go to market strategy of the organization as a modifier on the persona.",
                    "enum": ["b2b", "b2c", "b2d", "*"]
                }
            },
            "required": [],
            "additionalProperties": false
        },
        "awareness": {
            "description": "See traits/learning.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "description": "The business relationship between the persona's organization and yours.",
                    "enum": ["pro", "user", "partner", "lead", "unaware", "ex", "*"]
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "format": {
                                "type": "string",
                                "enum": ["blog", "newsletter", "video", "product", "docs", "social", "web"]
                            },
                            "url": {
                                "type": "string"
                            },
                            "level": {
                                "type": "string",
                                "enum": ["100", "200", "300", "*"]
                            }
                        }
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "additionalProperties": false
        },
        "adoption": {
            "description": "Adoption traits",
            "type": "object",
            "properties": {
                "curve": {
                    "type": "string",
                    "enum": ["innovator", "early", "majority", "late", "laggard", "*"]
                },
                "modality": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["problem", "learn", "understand", "info", "guide", "*"]
                    }
                }
            }
        },
        "role": {
            "description": "See traits/role.md for more detailed descriptions.",
            "type": "object",
            "properties": {
                "function": {
                    "type": "string",
                    "enum": ["dev", "art", "biz", "mix", "*"]
                },
                "experience": {
                    "description": "The stage of career is an indicator for how familiar a person may be with the skills and expectations of their role. \nThis attribute is about the progression for a specific role, not a person. Somebody may have extensive professional experience, but if they've taken on a new role in a new industry for the purposes of defining the persona it has reset the clock.",
                    "type": "string",
                    "enum": ["early", "mid", "pro", "*"]
                },
                "level": {
                    "type": "string",
                    "description": "The placement and influence this person has on the organization.",
                    "enum": ["ic", "lead", "exec", "infl", "*"]
                },
                "responsibilities": {
                    "type": "array",
                    "description": "The broad job tasks this persona must execute on as part of the duties of their role.",
                    "items": {
                        "type": "string",
                        "enum": ["coding", "reviewing", "planning", "reporting", "marketing", "financials", "strategy", "design", "writing", "*"]
                    }
                },
                "titles": {
                    "type": "array",
                    "description": "A list of typical job titles this persona may hold.",
                    "items": {
                        "type": "string"
                    }
                },
                "x-titles": {
                    "type": "array",
                    "description": "Extended set of titles for this persona. Merges instead of replaces.",
                    "items": {
                        "type": "string"
                    }
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-creative", "drf-test", "drf-build", "drf-cmm", "drf-email", "drf-cms", "drf-db"]
                    }
                },
                "x-tools": {
                    "type": "array",
                    "description": "Extended set of tools for this persona. Merges instead of replaces.",
                    "items": {
                        "type": "string",
                        "enum": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-creative", "drf-test", "drf-build", "drf-cmm", "drf-email", "drf-cms", "drf-db"]
                    }
                },
                "technologies": {
                    "type": "object",
                    "properties": {
                        "languages": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "environments": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "education": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "skills": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "required": ["responsibilities", "level"],
            "additionalProperties": false
        },
        "motivations": {
            "type": "object",
            "properties": {
                "likes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dislikes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "x-likes": {
                    "type": "array",
                    "description": "Additional extended likes that do not replace inherited definitions.",
                    "items": {
                        "type": "string"
                    }
                },
                "x-dislikes": {
                    "type": "array",
                    "description": "Additional extended dislikes that do not replace inherited definitions.",
                    "items": {
                        "type": "string"
                    }
                }

            },
            "additionalProperties": false
        },
        "strategies": {
            "type": "object",
            "properties": {
                "marketing": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sales": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "finance": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "design": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "devex": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "education": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "required": ["id", "label"],
    "additionalProperties": false
}

=== DevRel-Foundation/persona-library/data/personas/security-dev.json
{
    "id": "security-dev-majority-lead",
    "label": "Security Practitioner",
    "segment": "security",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    }, 
    "role": {
        "function": "dev",
        "level": "lead",
        "experience": "*",
        "responsibilities": ["coding", "reviewing", "planning", "reporting"],
        "tools": [],
        "titles": [
            "Software Engineer, Security",
            "Senior Research Engineer",
            "Application Security Engineer",
            "DevSecOps",
            "Network Engineer",
            "Security Engineer",
            "System Admin",
            "Security Sales Engineer",
            "Security Consultant",
            "Director of IT",
            "IT Security Analyst",
            "Sr. Information Security Lead",
            "Cyber Security Lead",
            "Red team / Pentester",
            "Cyber Threat Intelligence Advisor",
            "Information Security Architect",
            "Manager of Information Security",
            "Security Researcher"
        ]
    },
    "adoption": {
        "curve": "majority",
        "modality": ["learn", "understand", "problem"]
    },
    "awareness": {
        "channels": [
                {"format": "blog", "url": "https://thehackernews.com/"},
                {"format": "blog", "url": "https://www.darkreading.com/"},
                {"format": "newsletter", "url": "https://tldrsec.com/", "level":"300"},
                {"format": "newsletter", "url": "https://cloudseclist.com/"},
                {"format": "blog", "url": "https://dev.to/{your product}"}
        ],
        "events": [
            "drf-bsides.org",
            "drf-blackhat.com"
        ]
    },
    "motivations": {
        "likes": [
            "Works in small groups to team up on complex security projects"
        ],
        "dislikes": [
            "Cautious of strangers and those they do not know.",
            "Highly sensitive to sharing personal information that can be exploited. Won't easily sign up for a list."
        ]
    },
    "strategies": {
        "devex": [
            "Build simulations and test environments that provide a safe place to experiment and discover security flaws without risk of negative consequences."
        ]
    }
}

=== DevRel-Foundation/persona-library/data/sets/openssf.org/ssf-biz-mktg.json
{
    "id": "ssf-biz-mktg",
    "label": "Product Marketing and Community Engagement",
    "narrative": "Stays informed on open-source security trends in order to market a product or build connections between like-minded people.",
    "organization": {
        "gtm": "*",
        "maturity": "*"
    },
    "role": {
        "function": "biz",
        "level": "*",
        "experience": "*",
        "responsibilities": [],
        "titles": [
            "Public Relations Manager",
            "Community manager"
        ],
        "tools": [ ]
    },
    "awareness": {
        "channels": [ ],
        "events": [ ]
    },
    "motivations": {
        "likes": [
            "Networking, business development, and collaborating on go to market strategies."
        ],
        "dislikes": [
            "May find OpenSSF content and projects to be too technical or specific for broader marketing goals."
        ]
    },
    "strategies": {
        "design": [
        ],
        "product": [
        ],
        "education": [
            "Likes to learn from blog posts and case studies."
        ],
        "communications": [
            "Integration with other Linux Foundation projects the organization also relies upon.",
            "Cross-project engagement and enterprise adoption messaging."
        ],
        "sales": [
            "Partnership opportunities and media platforms is valuable."
        ],
        "marketing": [
            "Follows social media trends and supports those with professional relationships.",
            "Storytelling and marketing content is consumed and more effective than with other technical personas."
        ]
    }
}

=== DevRel-Foundation/persona-library/data/personas/biz.json
{
    "id": "biz",
    "label": "Product Marketing Pete",
    "narrative": "",
    "organization": {
        "gtm": "*",
        "maturity": "*"
    },
    "role": {
        "function": "biz",
        "level": "*",
        "experience": "*",
        "responsibilities": ["design", "writing"],
        "titles": [
            "Product Marketing Manager",
            "VP, Marketing"
        ],
        "tools": ["drf-cms", "drf-comms"]
    },
    "awareness": {
        "channels": [
                {"format": "blog", "url": "https://techcrunch.com"}
        ],
        "events": ["drf-techcrunch.com"]
    },
    "motivations": {
        "likes": [
            "Wants a clear understanding of why something is valuable or interesting."
        ],
        "dislikes": [
        ]
    },
    "strategies": {
        "design": [
        ],
        "product": [
        ],
        "education": [
            "A narrow case study or product page helps contextualize the problems and opportunities when not getting lost in the details."
        ],
        "communications": [
        ],
        "sales": [
        ],
        "marketing": [
        ]
    }
}

=== DevRel-Foundation/persona-library/data/personas/dev-python.json
{
    "id": "dev",
    "label": "Software Developer",
    "parent": ["dev"],
    "narrative": "A Python developer is a persona that has attached part of their professional identity to the Python community. They exhibit most of the same behaviors as the base developer persona but may consume additional channels, specific events, and have other motivations.",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "dev",
        "level": "*",
        "responsibilities": ["coding", "reviewing"],
        "x-titles": [
            "Python Developer"
        ],
        "x-tools": [],
        "technologies": {
            "languages": ["python"],
            "environments": [
             ],
            "skills": [ ],
            "education": [
                "B.S. Data Science"
            ]
        }
    },
    "awareness": {
        "channels": [
                {"format": "newsletter", "url": "https://pythonweekly.com"},
                {"format": "web", "url": "https://python.org"}
        ],
        "events": ["drf-pycon.org" ]
    },
    "adoption": {
        "curve": "*",
        "modality": []
    },
    "motivations": {
        "x-likes": [
            "Machine Laarning and Data Science professionals gravitate to languages like Python, Julia, and R."
        ],
        "x-dislikes": [
        ]
    },
    "strategies": {
        "design": [
        ],
        "product": [
        ],
        "education": [
            "Make sure any code samples provide appropriate indentation and formatting. Use a linter and PEP 8 style guide."
        ],
        "communications": [
        ],
        "sales": [
        ],
        "marketing": [
        ]
    }
}

=== DevRel-Foundation/persona-library/data/personas/ai-dev.json
{
    "id": "ai-dev",
    "parent": ["dev"],
    "label": "AI Alex",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "dev",
        "level": "*",
        "responsibilities": ["coding", "reviewing"],
        "titles": [
            "ML Engineer"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"],
        "technologies": {
            "languages": [ ],
            "environments": [ ],
            "skills": [ ]
        }
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://stackoverflow.com"}
        ],
        "events": [ ]
    },
    "adoption": {
        "curve": "*",
        "modality": []
    },
    "motivations": {
        "x-likes": [],
        "x-dislikes": [
        ]
    },
    "strategies": {
        "design": [],
        "product": [],
        "education": [],
        "communications": [],
        "sales": [],
        "marketing": []
    }
}

=== DevRel-Foundation/persona-library/data/personas/dev-exec.json
{
    "id": "dev-exec",
    "label": "Ed Exec",
    "narrative": "Deep technical experience over a long career. Has advanced their business understanding, but still rely on other experts for marketing, sales, finance, and other disciplines. Their decisions have major consequences for an entire organization.",
    "segment": "*",
    "organization": {
        "maturity": "*",
        "gtm": "*"
    },
    "role": {
        "function": "dev",
        "level": "lead",
        "experience": "pro",
        "responsibilities": ["strategy", "planning"],
        "titles": [
            "VP, Engineering",
            "Chief Technology Officer",
            "Chief Information Officer", 
            "Chief Information Security Officer"
        ],
        "tools": [ ],
        "technologies": {
            "languages": [ ],
            "environments": [ ],
            "skills": [ ]
        }
    },
    "awareness": {
        "channels": [
            {"format": "web", "url": "https://www.gartner.com/en/newsroom"},
            {"format": "blog", "url": "https://www.forrester.com/blogs/"},
            {"format": "blog", "url": "https://blogs.idc.com/"}
        ],
        "events": ["drf-leaddev.com", "drf-gartner.com"]
    },
    "adoption": {
        "curve": "*",
        "modality": []
    },
    "motivations": {
        "likes": [
        ],
        "dislikes": []
    },
    "strategies": {
        "design": [],
        "product": [],
        "education": [],
        "communications": [],
        "sales": [
            "Ask about their goals and strategy for their technical choices in the next year."
        ],
        "marketing": []
    }
}

=== DevRel-Foundation/persona-library/data/personas/mix-I-early-infl.json
{
    "id": "mix-I-early-infl",
    "label": "Andy Advocate",
    "segment": "*",
    "role": {
        "function": "mix",
        "responsibilities": ["coding", "reviewing"],
        "level": "infl",
        "titles": [
            "Developer Advocate",
            "Developer Evangelist",
            "Head of Developer Relations"
        ],
        "tools": ["drf-ide", "drf-scm", "drf-cicd", "drf-ticketing", "drf-comms", "drf-test", "drf-build"]
    },
    "adoption": {
        "curve": "early"
    },
    "awareness": {
        "channels": [
                {"format": "social", "url": "https://news.ycombinator.com"},
                {"format": "social", "url": "https://slashdot.org"}
        ],
        "events": ["drf-devrelcon.dev"]
    }
}

=== DevRel-Foundation/persona-library/data/personas/biz-security-early-exec.json
{
    "id": "biz-security-early-exec",
    "label": "Security Buyer",
    "segment": "security",
    "organization": {
        "maturity": "startup",
        "gtm": "b2b"
    }, 
    "role": {
        "function": "biz",
        "level": "exec",
        "experience": "pro",
        "responsibilities": ["financials", "strategy"],
        "titles": [
            "Chief Information Security Officer",
            "CISO",
            "VP, Security",
            "Head of Security"
        ]
    },
    "adoption": {
        "curve": "early",
        "modality": ["understand", "info"]
    },
    "awareness": {
        "channels": [
                {"format": "blog", "url": "https://${your-domain}.com/blog"},
                {"format": "product", "url": "https://${your-domain}.com/"},
                {"format": "blog", "url": "https://www.cio.com/", "level": "200"},
                {"format": "newsletter", "url": "https://tldrsec.com/", "level":"200"},
                {"format": "blog", "url": "https://krebsonsecurity.com/"},
                {"format": "newsletter", "url": "https://www.returnonsecurity.com/"}
        ],
        "events": [
            "drf-rsaconference.com"
        ]
    }
}
